### ISSUE TITLE
themes don't appear in archlinux-logout-git

### ISSUE THREAD

**Issue by mobsenpai** [arcolinux/arcolinux-logout-themes#1]
Hey Eric, just wanna know why the themes don't appear when I press settings gear icon in archlinux-logout?

**Comment by arcolinuxz** [comment]
depends what your are on... 
what package you have ...
on ArcoLinux it works

**Comment by mobsenpai** [comment]
Actually Eric, I went through and checked the files, as you teach us in your videos. I found that those themes get installed to /usr/share/arcologout-themes. But I've installed archlinux-logout whose themes should be in /usr/share/archlinux-logout-themes isn't it? Also I am on arcolinuxd (I love arco). Waiting for reply.

**Comment by arcolinuxz** [comment]
thanks for reporting
that is now fixed

name change needed for this one too
